import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Trips n Hops",
  description: "Generated by create next app",
};

import Header from "./_components/organisms/Header";
import Footer from "./_components/organisms/Footer";
import TrendingDestinations from "./_components/organisms/HomePage/TrendingDestinations";
import SectionA from "./_components/organisms/HomePage/SectionA";

export default function RootLayout({
  children,
  Hero,
  FeaturedTrips,
}: Readonly<{
  children: React.ReactNode;
  Hero: React.ReactNode;
  FeaturedTrips: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <main>
          <>
            <Header />
            {Hero}
            {children}
            {FeaturedTrips}
            <TrendingDestinations />
            <SectionA />
            <Footer />
          </>
        </main>
      </body>
    </html>
  );
}
